### PR TITLE
Fix MultipleVariableDeclarationsQuickFix comment handling

### PR DESCRIPTION
**Pull request by karlvr**
For variable declaration statements

### CODE REVIEW

**Comment by jdneo** [comment]
Is that because the new introduced replace() function?

I tried the existing `RequireThisQuickFix`, it will not remove the comments.

```java
public class TodoItemTest {

    private int i;

    public void test() {
        int i = 0;
        /** */
        i = i;
    }
}
```

**Comment by karlvr** [comment]
@jdneo thank you, I wanted to try that too. I'm not sure! I based the multi-replace on replace. I've tried using set to replace the original node rather than remove. Same problem.

**Comment by jdneo** [comment]
Opps, I don't know why this PR is closed when I merge the bump version PR. And I cannot reopen it.

@karlvr Can you reopen it on your side?

**Comment by jdneo** [comment]
Oh, It's because the PR is target to `cs/1.4.0`. Sorry I didn't notice that. Maybe raise a new one targeting the main branch?

**Pull request closed without merging**
