### PR TITLE
Add multiple variable declarations quick fix

### PR DESCRIPTION
**Pull request by karlvr**

### CODE REVIEW

**Comment by jdneo** [comment]
Not sure if it's related with my dev environment, but seems it's not working 🤔 
demo

**Comment by jdneo** [comment]
Ok, it's because we need to consider not only the field declaration but also variable declaration.
@karlvr Would you mind to update the PR to support variable declaration as well?

**Comment by karlvr** [comment]
@jdneo great catch, thank you.

**Review by jdneo — APPROVED** [review]
LGTM! Thanks @karlvr

**Pull request merged**
