### PR TITLE
fix: node_modules will be searched when detecting configuration

### LINKED ISSUE #242: node_modules will be searched when detecting configuration
Problems raised by it:
* Detection performance drop
* #237

### PR DESCRIPTION
**Pull request by Vigilans**
Fix #242 

`workspace.findFiles` by default will **NOT** exclude `node_modules`, because it only uses `files.exclude` setting, where `node_modules` is in `search.exclude` and `.gitignore`.
 - **reference**: https://github.com/Microsoft/vscode/issues/48674, an problem which is aware of by vscode team
 - **fix**: Introduce a new funciton, excludes all of `files.exclude`, `search.exclude` and `.gitignore`, like https://github.com/Microsoft/vscode/issues/48674#issuecomment-422950502

### CODE REVIEW

**Comment by jdneo** [comment]
This pull request **introduces 1 alert** when merging fcddcd98b5d1b24b0c15992981c2fbd1247bc1d8 into 79239147f05545d6d2920971f14de5eebb334b07 - [view on LGTM.com](https://lgtm.com/projects/g/jdneo/vscode-checkstyle/rev/pr-ea7a57741e305d22639fde1e811aeb78d3b57a1e)

**new alerts:**

* 1 for Template syntax in string literal

---

**Warning** - Automated code review for jdneo/vscode-checkstyle will be disabled on October 1, 2019. You can avoid this by <a href="https://github.com/apps/lgtm-com/installations/new">installing the LGTM.com GitHub App</a>. Read about the <a href="https://lgtm.com/blog/announcing_github_apps_migration">benefits of migrating to GitHub Apps</a> in the blog.

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by jdneo** [comment]
This pull request **introduces 1 alert** when merging a4205700b6a03e51069c74062f225eb24c2209e3 into 79239147f05545d6d2920971f14de5eebb334b07 - [view on LGTM.com](https://lgtm.com/projects/g/jdneo/vscode-checkstyle/rev/pr-39e2d6afac2248d1000d52a1c053af003828627e)

**new alerts:**

* 1 for Template syntax in string literal

---

**Warning** - Automated code review for jdneo/vscode-checkstyle will be disabled on October 1, 2019. You can avoid this by <a href="https://github.com/apps/lgtm-com/installations/new">installing the LGTM.com GitHub App</a>. Read about the <a href="https://lgtm.com/blog/announcing_github_apps_migration">benefits of migrating to GitHub Apps</a> in the blog.

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by Vigilans** [comment]
> This pull request **introduces 1 alert** when merging [a420570](https://github.com/jdneo/vscode-checkstyle/commit/a4205700b6a03e51069c74062f225eb24c2209e3) into [7923914](https://github.com/jdneo/vscode-checkstyle/commit/79239147f05545d6d2920971f14de5eebb334b07) - [view on LGTM.com](https://lgtm.com/projects/g/jdneo/vscode-checkstyle/rev/pr-39e2d6afac2248d1000d52a1c053af003828627e)
> 
> **new alerts:**
> 
> * 1 for Template syntax in string literal
> 
> **Warning** - Automated code review for jdneo/vscode-checkstyle will be disabled on October 1, 2019. You can avoid this by [installing the LGTM.com GitHub App](https://github.com/apps/lgtm-com/installations/new). Read about the [benefits of migrating to GitHub Apps](https://lgtm.com/blog/announcing_github_apps_migration) in the blog.
> 
> _Comment posted by [LGTM.com](https://lgtm.com)_

This alert could be dismissed, as it is the error message 'workspaceFolder not loaded when ${workspaceFolder} is present'.

**Comment by jdneo** [comment]
This pull request **introduces 1 alert** when merging d8a8fab8690bba1aacbaeaa79cd65086533dc0d1 into d9dc7a9e7d6dbe3f17382072597397cf12c1ddf5 - [view on LGTM.com](https://lgtm.com/projects/g/jdneo/vscode-checkstyle/rev/pr-7ae5b07711d18ff27ae3b0a216a3fbdd197d7c95)

**new alerts:**

* 1 for Template syntax in string literal

---

**Warning** - Automated code review for jdneo/vscode-checkstyle will be disabled on October 1, 2019. You can avoid this by <a href="https://github.com/apps/lgtm-com/installations/new">installing the LGTM.com GitHub App</a>. Read about the <a href="https://lgtm.com/blog/announcing_github_apps_migration">benefits of migrating to GitHub Apps</a> in the blog.

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by jdneo** [comment]
This pull request **introduces 1 alert** when merging b1f675f3f3e7bb84c845b2d525cf324d88fd064e into d9dc7a9e7d6dbe3f17382072597397cf12c1ddf5 - [view on LGTM.com](https://lgtm.com/projects/g/jdneo/vscode-checkstyle/rev/pr-93e93ba5554ab6d5398a62f1be49b37eaeaabf42)

**new alerts:**

* 1 for Template syntax in string literal

---

**Warning** - Automated code review for jdneo/vscode-checkstyle will be disabled on October 1, 2019. You can avoid this by <a href="https://github.com/apps/lgtm-com/installations/new">installing the LGTM.com GitHub App</a>. Read about the <a href="https://lgtm.com/blog/announcing_github_apps_migration">benefits of migrating to GitHub Apps</a> in the blog.

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Pull request merged**
